export default {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_COMPLETE: "LOGIN_COMPLETE",
  LOGIN_FAIL: "LOGIN_FAIL",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_COMPLETE: "SIGN_UP_COMPLETE",
  SIGN_UP_FAIL: "SIGN_UP_FAIL",

  OTP_REQUEST: "OTP_REQUEST",
  OTP_COMPLETE: "OTP_COMPLETE",
  OTP_FAIL: "OTP_FAIL",

  USER_VERIFICATION_REQUEST: "USER_VERIFICATION_REQUEST",
  USER_VERIFICATION_COMPLETE: "USER_VERIFICATION_COMPLETE",
  USER_VERIFICATION_FAIL: "USER_VERIFICATION_FAIL",

  SET_LANGUAGE: "SET_LANGUAGE",
};
